export enum ReviewsActionTypes {
  GET_REVIEWS = 'GET_REVIEWS',
  GET_REVIEWS_COMPLETE = 'GET_REVIEWS_COMPLETE',
  GET_REVIEWS_FAILED = 'GET_REVIEWS_FAILED',

  GET_ALL_REVIEWS = 'GET_ALL_REVIEWS',
  GET_ALL_REVIEWS_COMPLETE = 'GET_ALL_REVIEWS_COMPLETE',
  GET_ALL_REVIEWS_FAILED = 'GET_ALL_REVIEWS_FAILED'
}
